### ISSUE TITLE
the .mdb file

### ISSUE THREAD

**Issue by Jx-Tan** [Shanghai-Aitrox-Technology/EfficientSegmentation#1]
I want to use other data sets. Do I need to modify this file and how should I modify it（data.mdb）？

**Comment by thapaliya19** [comment]
I'm trying to do the same. Seems like we need to change the `data.mdb` file inside `DEFAULT_TRAIN_DB` and `DEFAULT_VAL_DB` directories. Is there any way to change these files? @Shanghai-Aitrox-Technology

**Comment by Shanghai-Aitrox-Technology** [comment]
@Jx-Tan @thapaliya19 If you want to use another data sets, you should _run data processing_ with reference to _Get Started._
