### ISSUE TITLE
Potentially Faster CCL Extraction

### ISSUE THREAD

**Issue by william-silversmith** [Shanghai-Aitrox-Technology/EfficientSegmentation#3]
Hi! 

I'm the author of cc3d and from time to time I search GitHub to see how people are using the library. I noticed that there are a few places that could *potentially* see some improvement even though you clearly made use of many of cc3d's tricks.

https://github.com/Shanghai-Aitrox-Technology/EfficientSegmentation/blob/5a8eda57fe75bbd74740c8dd75404076cb5aa9c2/Common/mask_process.py#L85-L112

cc3d has some very efficient functions for performing these two tasks. [`cc3d.dust`](https://github.com/seung-lab/connected-components-3d/blob/master/cc3d.pyx#L1008-L1056) and [`cc3d.largest_k`](https://github.com/seung-lab/connected-components-3d/blob/master/cc3d.pyx#L1058-L1106). You might be surprised at the improvement.

Anywho, if this isn't helpful to your project feel free to ignore these tips. Thanks for using cc3d!

Will

**Comment by Shanghai-Aitrox-Technology** [comment]
@william-silversmith 3Q for your comments.
